export interface SB_CarForRentModel {
  id: number;
  group: string;
  brand: string;
  year?: number;
  passenger_capacity: number;
  luggage_capacity: number;
  transmission: string;
  travel_conditions?: string;
  fuel_type?: string;
  renter_id: number;
  owner_id?: number | null;
  pick_up_location: string;
  available: boolean;
  rent_per_day: number;
  rental_duraction_days?: number;
  details?: string;
  created_at?: string;
  car_doors: number;
  air_conditioning?: boolean;
  power_steering?: boolean;
  front_airbags?: boolean;
  radio?: boolean;
  central_locking?: boolean;
  abs?: boolean;
  fuel_consumption: string;
  engine: string;
  tank_capacity: number;
  trunk_capacity: number;
  url_img: string;
}
